<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Services/Ordering/ShopSphere.Ordering.Domain/ShopSphere.Ordering.Domain.csproj" />
    <ProjectReference Include="../../src/Services/Inventory/ShopSphere.Inventory.Domain/ShopSphere.Inventory.Domain.csproj" />
    <ProjectReference Include="../../src/Services/Payment/ShopSphere.Payment.Domain/ShopSphere.Payment.Domain.csproj" />
    <ProjectReference Include="../../src/Services/Payment/ShopSphere.Payment.Infrastructure/ShopSphere.Payment.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Gateway/ShopSphere.Gateway/ShopSphere.Gateway.csproj" />
    <ProjectReference Include="../../src/Services/Catalog/ShopSphere.Catalog.Infrastructure/ShopSphere.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Services/Basket/ShopSphere.Basket.Application/ShopSphere.Basket.Application.csproj" />
    <ProjectReference Include="../../src/Services/Basket/ShopSphere.Basket.Infrastructure/ShopSphere.Basket.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Services/Inventory/ShopSphere.Inventory.Infrastructure/ShopSphere.Inventory.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Workers/ShopSphere.Notification.Worker/ShopSphere.Notification.Worker.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
</Project>
