// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopSphere.Catalog.Infrastructure;

#nullable disable

namespace ShopSphere.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDb))]
    [Migration("20261007035400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopSphere.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Brand = "Apple",
                            Category = "Laptops",
                            Description = "A light, powerful laptop for everyday creative work. 13-inch display, 16 GB memory, 256 GB SSD.",
                            ImageUrl = "/products/laptop.svg",
                            Name = "MacBook Air M4",
                            Price = 999m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Brand = "Sony",
                            Category = "Audio",
                            Description = "Wireless over-ear headphones with noise cancellation and up to 30 hours of battery life.",
                            ImageUrl = "/products/headphones.svg",
                            Name = "WH-1000XM5",
                            Price = 299m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Brand = "Logitech",
                            Category = "Accessories",
                            Description = "A comfortable wireless mouse with quiet clicks, precise scrolling and USB-C charging.",
                            ImageUrl = "/products/mouse.svg",
                            Name = "MX Master 3S",
                            Price = 99m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Brand = "Apple",
                            Category = "Monitors",
                            Description = "A bright 27-inch 5K display for your desk, with an integrated camera and speakers.",
                            ImageUrl = "/products/monitor.svg",
                            Name = "Studio Display",
                            Price = 1599m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Brand = "Keychron",
                            Category = "Accessories",
                            Description = "A compact wireless mechanical keyboard with a tactile typing feel and a durable aluminum frame.",
                            ImageUrl = "/products/keyboard.svg",
                            Name = "Keychron K2",
                            Price = 89m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Brand = "Samsung",
                            Category = "Storage",
                            Description = "1 TB of fast, portable storage in a pocket-sized aluminum enclosure.",
                            ImageUrl = "/products/ssd.svg",
                            Name = "Portable SSD T7",
                            Price = 109m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
