export type Product = { id: string; name: string; description: string; price: number; imageUrl: string; brand: string; category: string; isActive: boolean; version: number };
export type CatalogProduct = Pick<Product, "id" | "name" | "description" | "price" | "imageUrl" | "brand" | "category"> & { availableQuantity: number | null };
export type ProductPage = { items: CatalogProduct[]; page: number; pageSize: number; totalCount: number; totalPages: number };
export type StockAvailability = Pick<Stock, "productId" | "availableQuantity">;
export type BasketItem = { productId: string; name: string; unitPrice: number; quantity: number; imageUrl: string; availableQuantity: number; isAvailable: boolean };
export type Basket = { customerId: string; items: BasketItem[]; total: number; canCheckout: boolean };
export type Stock = { productId: string; availableQuantity: number; reservedQuantity: number };
export type Order = { id: string; customerId: string; customerName: string; email: string; totalAmount: number; status: string; cancellationReason?: string; createdAt: string; items: BasketItem[] };
export type Payment = { orderId: string; status: string; amount: number; currency: string; checkoutUrl: string | null; mode: "Demo" | "Stripe" };
